//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VecApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   イニシャライズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウントチェック1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウントチェック2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZXスケール軸 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   温度センサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ復元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーム型式設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///    アーム型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アームネットワーク設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレス： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブネットマスク： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点間ピッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャナパラメータ詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オート
        ///メッシング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ
        ///初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輝度マスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動(1パッチ毎) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動(スタート毎) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   距離マスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点群補正/フィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輝度スライス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///    スタイラス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感度スライス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイドレーザーパワー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補間(Xピッチ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度マスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2ピークマスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ有効(波形幅広) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボール： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ有効(近距離) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エッジマスク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効輝度データ上限範囲： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効輝度データ下限範囲： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基準輝度算出データ数： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直径： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基準輝度算出データ幅： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示範囲と輝度マスクを連動させる： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下限輝度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上限輝度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小輝度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均輝度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大輝度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   範囲外点群
        ///を削除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラフ表示範囲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   始業前点検 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   近 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラインの両端は使用しない： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン間を補正する： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   斜面のきつい部分は使用しない： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点間がしきい値を超える場合には使用しない： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   両側点角度がしきい値を超える場合は使用しない： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   穴認識 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   角度： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタンダード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドバンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エッジマスク点数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点間ピッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャナパラメータ詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボール直径： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オート
        ///メッシング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ
        ///初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非接触始業前点検 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String196 {
            get {
                return ResourceManager.GetString("String196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String197 {
            get {
                return ResourceManager.GetString("String197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャナSW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String198 {
            get {
                return ResourceManager.GetString("String198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラッチ通信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String199 {
            get {
                return ResourceManager.GetString("String199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暖機待ち処理: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    アーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポインタ位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String200 {
            get {
                return ResourceManager.GetString("String200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モーター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String201 {
            get {
                return ResourceManager.GetString("String201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String202 {
            get {
                return ResourceManager.GetString("String202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String203 {
            get {
                return ResourceManager.GetString("String203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全点灯 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String204 {
            get {
                return ResourceManager.GetString("String204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全消灯 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String205 {
            get {
                return ResourceManager.GetString("String205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String206 {
            get {
                return ResourceManager.GetString("String206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String207 {
            get {
                return ResourceManager.GetString("String207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャナネットワーク設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String208 {
            get {
                return ResourceManager.GetString("String208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレス： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String209 {
            get {
                return ResourceManager.GetString("String209", resourceCulture);
            }
        }
        
        /// <summary>
        ///    スキャナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブネットマスク： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String210 {
            get {
                return ResourceManager.GetString("String210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルトゲートウェイ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String211 {
            get {
                return ResourceManager.GetString("String211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String212 {
            get {
                return ResourceManager.GetString("String212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String213 {
            get {
                return ResourceManager.GetString("String213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタンダード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String214 {
            get {
                return ResourceManager.GetString("String214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクステンション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String215 {
            get {
                return ResourceManager.GetString("String215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String216 {
            get {
                return ResourceManager.GetString("String216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String217 {
            get {
                return ResourceManager.GetString("String217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージ長さ: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String218 {
            get {
                return ResourceManager.GetString("String218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String219 {
            get {
                return ResourceManager.GetString("String219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しきい値設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String220 {
            get {
                return ResourceManager.GetString("String220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String221 {
            get {
                return ResourceManager.GetString("String221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0軸イニシャライズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String222 {
            get {
                return ResourceManager.GetString("String222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モード切替 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String223 {
            get {
                return ResourceManager.GetString("String223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触設定メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String224 {
            get {
                return ResourceManager.GetString("String224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アライメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String225 {
            get {
                return ResourceManager.GetString("String225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非接触設定メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String226 {
            get {
                return ResourceManager.GetString("String226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   測定モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String227 {
            get {
                return ResourceManager.GetString("String227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(有) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String228 {
            get {
                return ResourceManager.GetString("String228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(非) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String229 {
            get {
                return ResourceManager.GetString("String229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ点検 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準プローブを取り付けて下さい(ID2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String230 {
            get {
                return ResourceManager.GetString("String230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String231 {
            get {
                return ResourceManager.GetString("String231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置エラーと測定誤差許容値オーバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String232 {
            get {
                return ResourceManager.GetString("String232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   測定誤差許容値オーバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String233 {
            get {
                return ResourceManager.GetString("String233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String234 {
            get {
                return ResourceManager.GetString("String234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String235 {
            get {
                return ResourceManager.GetString("String235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String236 {
            get {
                return ResourceManager.GetString("String236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トリガボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String237 {
            get {
                return ResourceManager.GetString("String237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセルボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String238 {
            get {
                return ResourceManager.GetString("String238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行ボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String239 {
            get {
                return ResourceManager.GetString("String239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大-最小 しきい値： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アームロックボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String240 {
            get {
                return ResourceManager.GetString("String240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各ボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String241 {
            get {
                return ResourceManager.GetString("String241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファームウェアのバージョンが表示されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String242 {
            get {
                return ResourceManager.GetString("String242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String243 {
            get {
                return ResourceManager.GetString("String243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各関節の通信が正常か確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String244 {
            get {
                return ResourceManager.GetString("String244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての関節を動かして正常動作しているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String245 {
            get {
                return ResourceManager.GetString("String245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イニシャライズ位置を反復回転させてゼロ付近になるか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String246 {
            get {
                return ResourceManager.GetString("String246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z、Xスケールを動かして正常動作しているか確認してください。
        ///ファームウェアのバージョンが表示されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String247 {
            get {
                return ResourceManager.GetString("String247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のアーム内温度と校正時のアーム内温度が表示されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String248 {
            get {
                return ResourceManager.GetString("String248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Counter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String249 {
            get {
                return ResourceManager.GetString("String249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2σ しきい値： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スケール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String250 {
            get {
                return ResourceManager.GetString("String250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーム内温度(℃) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String251 {
            get {
                return ResourceManager.GetString("String251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   校正時温度(℃) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String252 {
            get {
                return ResourceManager.GetString("String252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面間距離 しきい値： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球中心(球ゲージ)： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球直径(球ゲージ)： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブID： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャナ接続手順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリブレーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージ配置距離： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージ配置高さ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリブレーション誤差許容値： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲージタイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球中心 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///    [ スキャナ接続手順 ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面高さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面間距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出ポイント: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出半径: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直径: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出球数: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許容値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必要最小点数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感度チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. スキャナをアームに接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球中心: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面高さ: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面間距離: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球中心(球ゲージ): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基準感度: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許容範囲: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリブレーション開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. 起動完了ブザーを確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マルチゲージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   球 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーム型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリブレーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. [接続完了]ボタンをクリック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自己判断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触 プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ情報入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボール直径： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブタイプ： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触始業前点検 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大-最小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚠️ スキャナユニットが落下しないように
        ///     注意して取り付けてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   面間距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   測定誤差 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初めに戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブキャリブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触キャリブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プローブ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スナップショット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///    ボールスタイラス直径 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///    面間基準距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///    ボールゲージ直径 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///    球径警告値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有接触自己判断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スイッチ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファームウェアVer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウンタ Ver. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
